# inputs that are available before the whole configuration has been built

# consider pkgs. it needs to know what system is being used which is specified as a direct input to nixosSystem function
# this then

/*
  identify this flake's inputs and make sure that all of those have their outputs available
  now we import all the n.mod.nix files and run their functions with other flake's outputs. we dont have access to anything generated by our flake
  some processing of the resulting nix expressions leads to a list of modules and home_modules.
  these modules can be functions that take inputs. These inputs can be various things
    - other flake outputs by passing them through to specialArgs or extraSpecialArgs for home manager. Note self does not give access to inputs
    - self, which is this flake which gives access to other outputs of this flake. this is practicaly giving access to other outputs inside an output.
    - config, which is available inside of modules, it gives access to configuration in any other module
*/

{ niri, ags_system, ... }:
{
  universal.modules = [
    niri.nixosModules.niri

    (
      { pkgs, ... }:
      {
        programs.niri.enable = true;
        nixpkgs.overlays = [ niri.overlays.niri ];
        programs.niri.package = pkgs.niri-unstable;
      }
    )
  ];

  universal.home_modules = [

    (
      { config, ... }:
      {
        programs.niri.settings = {
          input.keyboard.xkb.layout = "se";

          layout = {
            default-column-width = {
              proportion = 1.0;
            };
            gaps = 0;
            preset-column-widths = [
              { proportion = 1. / 3.; }
              { proportion = 1. / 2.; }
              { proportion = 2. / 3.; }
              #{ proportion = 1.0; }

              # { fixed = 1920; }
            ];
            focus-ring = {
              enable = false;
              #   width = 10000;
              #   active.color = "#00000055";
            };

          };
          spawn-at-startup = [
            { command = [ "${ags_system.packages.x86_64-linux.default}/bin/my-shell" ]; }
          ];

          binds = with config.lib.niri.actions; {
            "Mod+T".action = spawn "alacritty";
            "Mod+D".action = spawn "fuzzel";
            "Mod+Q".action = close-window;
            "Mod+O".action = spawn "ags" "request" "toggle";

            "Mod+Left".action = focus-column-left;
            "Mod+Right".action = focus-column-right;
            "Mod+Down".action = focus-window-down;
            "Mod+Up".action = focus-window-up;
            "Mod+H".action = focus-column-left;
            "Mod+L".action = focus-column-right;
            "Mod+J".action = focus-window-down;
            "Mod+K".action = focus-window-up;

            "Mod+Ctrl+Left".action = move-column-left;
            "Mod+Ctrl+Down".action = move-window-down;
            "Mod+Ctrl+Up".action = move-window-up;
            "Mod+Ctrl+Right".action = move-column-right;
            "Mod+Ctrl+H".action = move-column-left;
            "Mod+Ctrl+J".action = move-window-down;
            "Mod+Ctrl+K".action = move-window-up;
            "Mod+Ctrl+L".action = move-column-right;

            "Mod+F".action = maximize-column;
            "Mod+Shift+F".action = fullscreen-window;

            "Mod+R".action = switch-preset-column-width;
            "Mod+Shift+R".action = switch-preset-window-height;

            "Mod+Shift+S".action = screenshot; # {write-to-disk = true;};
            #"Ctrl+Print".action.screenshot-screen = {write-to-disk = true;};
            #"Alt+Print".action.screenshot-window = {write-to-disk = true;};

            # Powers off the monitors. To turn them back on, do any input like
            # moving the mouse or pressing any other key.
            "Mod+Shift+P".action = power-off-monitors;

            # The quit action will show a confirmation dialog to avoid accidental exits.
            "Mod+Shift+E".action = quit;
          };
          # spawn-at-startup = [];
        };
      }
    )
  ];
  igniter.home_modules = [
    {
      programs.niri.settings = {

        outputs = {
          /*
            "HDMI-A-1" = {
                     enable = false;
                     mode.width = 3840;
                     mode.height = 2160;
                     mode.refresh = 60.0;
                     position.x = 0;
                     position.y = -cfg."HDMI-A-1".mode.height;
                   };
          */
          "DP-1" = {
            #     2560x1440@164.802
            mode.width = 2560;
            mode.height = 1440;
            mode.refresh = 164.802;
            position.x = 0;
            position.y = 0;
          };
        };

      };
    }
  ];
  strategist.home_modules = [
    {
      programs.niri.settings = {

        outputs = {
          "eDP-1" = {
            mode.width = 2880;
            mode.height = 1800;
            mode.refresh = 60.001;
            position.x = 0;
            position.y = 0;
          };
        };

      };

      # niri msg outputs
      # Output "California Institute of Technology 0x1416 Unknown" (eDP-1)
      #   Current mode: 2880x1800 @ 60.001 Hz (preferred)
      #   Variable refresh rate: supported, disabled
      #   Physical size: 300x190 mm
      #   Logical position: 0, 0
      #   Logical size: 1645x1028
      #   Scale: 1.75
      #   Transform: normal
      #   Available modes:
      #     2880x1800@60.001 (current, preferred)
      #     2880x1800@120.000
      #     1920x1200@60.001
      #     1920x1080@60.001
      #     1600x1200@60.001
      #     1680x1050@60.001
      #     1280x1024@60.001
      #     1440x900@60.001
      #     1280x800@60.001
      #     1280x720@60.001
      #     1024x768@60.001
      #     800x600@60.001
      #     640x480@60.001
    }
  ];

}
